const TRANSLATIONS = {
    en: {
        menu:{play:'Play',continue:'Continue',bestiary:'Bestiary',workshop:'Workshop',options:'Options',language:'Language',controls:'WASD Move · Mouse Aim · Space Jump · Shift Dash · Q Power · Esc Pause'},
        setup:{startingRound:'Starting Round',difficulty:'Difficulty',round:'Round {round}',loadout:'Loadout',generated:'Generated',standard:'Standard',advanced:'Advanced Start',eligibility:'High Score Eligibility',descriptionLow:'Slower abilities, longer warnings and more recovery opportunities.',descriptionStandard:'Standard enemy behavior, balanced bosses and normal rewards.',descriptionHigh:'Faster abilities, more elite enemies and more complex boss patterns.',descriptionExtreme:'Maximum aggression, advanced boss variants and minimal recovery opportunities.',difficultyHint:'100% is the normal game. Lower is easier, higher is harder.',easier:'Easier',normal:'Normal',harder:'Harder',briefing:'Run Setup'},
        loadout:{title:'Starting Loadout',start:'Start',reroll:'Reroll Loadout',health:'Maximum health',movement:'Movement speed',damage:'Damage',fireRate:'Fire rate',jump:'Jump cooldown',armor:'Damage reduction',weapon:'Weapon level'},
        pause:{title:'DEADBOX · Paused',resume:'Resume',menu:'Main Menu'},
        common:{back:'Back',on:'On',off:'Off',unknown:'Unknown'},
        options:{title:'Options',master:'Master volume',music:'Music volume',effects:'Sound effects',shake:'Screen shake',damageNumbers:'Damage numbers',fullscreen:'Fullscreen',language:'Language',reducedEffects:'Reduced effects'},
        bestiary:{title:'Bestiary',all:'All',discovered:'Discovered',undiscovered:'Undiscovered',mostDefeated:'Most defeated',category:'Category',firstSeen:'First round',defeated:'Defeated',maxDifficulty:'Highest difficulty',variants:'Elite traits',behavior:'Behavior',ability:'Ability',locked:'Encounter this enemy to reveal its entry.',killLocked:'Defeat this enemy to reveal full details.'},
        gameOver:{title:'DEADBOX · Game Over',retry:'Retry',menu:'Main Menu',stats:'Round {round} · Score {score} · Defeated {kills}',scrap:'+{amount} Scrap'},
        tutorial:{move:'WASD to move · Mouse to aim',jump:'Press SPACE to jump over enemies',dash:'Press SHIFT to dash through danger',power:'Press Q to use a power when you have one'},
        upgrade:{title:'Round Clear',prompt:'Choose one upgrade',selected:'Upgrade applied',next:'Next round'},
        hud:{score:'Score {score}',combo:'×{combo} · {kills} chain',round:'Round {round} · {time}s · {name}',safePause:'Upgrade pause',preparing:'Preparing',weapon:'Weapon Lv. {level}',jumpReady:'Jump Ready',jumpBlocked:'Jump Disabled',jumpTime:'Jump {time}s',dashReady:'» Shift · Ready',dashActive:'» Shift · Dashing',dashCharges:'» Shift · {count} charges',dashTime:'» Shift · {time}s',shieldHit:'{count} charge',shieldHits:'{count} charges',arenaCleared:'Arena cleared!',runScrap:'+{amount} Scrap'},
        records:{line:'Best {score} · Round {round}',scrapTotal:'{amount} Scrap saved',bestLabel:'Best',scrapLabel:'Scrap',bestValue:'{score} · R{round}'},
        boss:{phase:'{name} · Phase {phase}',miniboss:'Miniboss',arrival:'{name}',defeated:'Target down'},
        recovery:{title:'Interrupted Run',body:'An interrupted run was found.',continue:'Continue Run',new:'New Run'},
        messages:{powerStolen:'Power disabled: {name}',powerRestored:'Power restored: {name}',weaponUp:'Weapon level {level}'},
        categories:{all:'All categories',common:'Common',agile:'Agile',heavy:'Heavy',ranged:'Ranged',support:'Support',hazard:'Hazard',summoner:'Summoner',elite:'Elite',miniboss:'Miniboss',boss:'Boss',invocation:'Invocation',control:'Control'},
        zones:{containment:'Containment',foundry:'The Foundry',bloom:'Bloom',cryo:'Cryo Deck',void:'The Void',ember:'Emberfall',null:'Null Sector'},
        workshop:{title:'Workshop',box:'Box',gun:'Gun',bullet:'Bullet',hint:'Looks only — nothing here changes how the game plays.',buy:'Buy {price}',equip:'Equip',equipped:'Equipped',locked:'Need {price}',scrap:'{amount} Scrap'},
        cosmetics:{
            box:{default:'Standard',crimson:'Crimson',toxic:'Toxic',void:'Void',bone:'Bone',gold:'Gold'},
            gun:{default:'Standard',snub:'Snub',heavy:'Heavy',twin:'Twin',lance:'Lance',gold:'Gold'},
            bullet:{default:'Standard',plasma:'Plasma',ember:'Ember',shard:'Shard',venom:'Venom',gold:'Gold'}
        },
        upgrades:{maxHealth:['Vital Frame','+20 maximum health and restore 50%'],heal:['Field Kit','Restore all health'],speed:['Mobility','Movement speed +12%'],damage:['Caliber','Permanent damage +5'],fireRate:['Cycler','Fire interval -9%'],agility:['Recovery','Jump cooldown -0.8s'],armor:['Plating','Damage received -8%'],shield:['Barrier','Block the next hit'],dashDistance:['Dash Distance','Dash range +12%'],dashSpeed:['Dash Speed','Dash execution +12%'],dashRecovery:['Dash Recovery','Dash cooldown -0.35s'],dashShield:['Dash Shield','Dash protection +45ms'],shockDash:['Shock Dash','Dash pushes enemies in its path'],trailBurn:['Trail Burn','Dash leaves a short damaging trail'],doubleDash:['Double Dash','Gain a second dash charge'],scatter:['Scatter','One more projectile in a wider fan'],lance:['Lance','Shots pierce one more enemy'],ricochet:['Ricochet','Shots bounce one more time off walls'],arc:['Arc','Shots jump to nearby enemies'],siege:['Siege','Far heavier shots, slower fire rate']},
        powers:{selfDestruct:['Self-Destruct','Q · 1 charge'],ghost:['Ghost','Invulnerable and untargetable for 7 seconds.'],overdrive:['Overdrive Dash','Enhanced dash for 8.5 seconds.'],backfire:['Backfire','Fire backward for 9 seconds.'],orbitals:['Orbitals','Four protective orbitals for 10 seconds.'],timeFreeze:['Time Freeze','Enemies heavily slowed for 6.5 seconds.'],bulletStorm:['Bullet Storm','Rapid fire for 7 seconds.'],ricochet:['Ricochet','Shots rebound once for 9 seconds.'],chainLightning:['Chain Lightning','Shots chain to nearby targets for 8 seconds.'],gravityWell:['Gravity Well','Pull enemies into a field for 8 seconds.'],giant:['Giant Mode','Larger, stronger and slower for 9 seconds.'],miniMode:['Mini Mode','Smaller and faster for 9 seconds.'],piercingCore:['Piercing Core','Shots pierce several targets for 9 seconds.'],clone:['Clone','A firing copy follows for 8.5 seconds.']}
    },
    es: {
        menu:{play:'Jugar',continue:'Continuar',bestiary:'Bestiario',workshop:'Taller',options:'Opciones',language:'Idioma',controls:'WASD Mover · Ratón Apuntar · Espacio Saltar · Shift Dash · Q Poder · Esc Pausa'},
        setup:{startingRound:'Ronda inicial',difficulty:'Dificultad',round:'Ronda {round}',loadout:'Equipamiento',generated:'Generado',standard:'Estándar',advanced:'Inicio avanzado',eligibility:'Elegibilidad del récord',descriptionLow:'Habilidades más lentas, advertencias largas y más oportunidades de recuperación.',descriptionStandard:'Comportamiento estándar, bosses equilibrados y recompensas normales.',descriptionHigh:'Habilidades más rápidas, más élites y patrones de boss más complejos.',descriptionExtreme:'Agresividad máxima, variantes avanzadas y pocas oportunidades de recuperación.',difficultyHint:'100% es el juego normal. Menos es más fácil, más es más difícil.',easier:'Más fácil',normal:'Normal',harder:'Más difícil',briefing:'Configuración'},
        loadout:{title:'Equipamiento inicial',start:'Comenzar',reroll:'Regenerar equipamiento',health:'Vida máxima',movement:'Velocidad',damage:'Daño',fireRate:'Cadencia',jump:'Recarga de salto',armor:'Reducción de daño',weapon:'Nivel de arma'},
        pause:{title:'DEADBOX · Pausa',resume:'Continuar',menu:'Menú principal'},
        common:{back:'Volver',on:'Sí',off:'No',unknown:'Desconocido'},
        options:{title:'Opciones',master:'Volumen general',music:'Volumen de música',effects:'Efectos de sonido',shake:'Movimiento de pantalla',damageNumbers:'Números de daño',fullscreen:'Pantalla completa',language:'Idioma',reducedEffects:'Efectos reducidos'},
        bestiary:{title:'Bestiario',all:'Todos',discovered:'Descubiertos',undiscovered:'No descubiertos',mostDefeated:'Más eliminados',category:'Categoría',firstSeen:'Primera ronda',defeated:'Eliminados',maxDifficulty:'Mayor dificultad',variants:'Rasgos élite',behavior:'Comportamiento',ability:'Habilidad',locked:'Encuentra este enemigo para revelar su entrada.',killLocked:'Elimina este enemigo para revelar todos los detalles.'},
        gameOver:{title:'DEADBOX · Fin de partida',retry:'Reintentar',menu:'Menú principal',stats:'Ronda {round} · Puntuación {score} · Eliminados {kills}',scrap:'+{amount} de chatarra'},
        tutorial:{move:'WASD para moverte · Ratón para apuntar',jump:'Pulsa ESPACIO para saltar sobre los enemigos',dash:'Pulsa SHIFT para atravesar el peligro',power:'Pulsa Q para usar un poder cuando tengas uno'},
        upgrade:{title:'Ronda completada',prompt:'Elige una mejora',selected:'Mejora aplicada',next:'Siguiente ronda'},
        hud:{score:'Puntuación {score}',combo:'×{combo} · cadena {kills}',round:'Ronda {round} · {time}s · {name}',safePause:'Pausa de mejoras',preparing:'Preparando',weapon:'Arma Nv. {level}',jumpReady:'Salto listo',jumpBlocked:'Salto bloqueado',jumpTime:'Salto {time}s',dashReady:'» Shift · Listo',dashActive:'» Shift · Dash',dashCharges:'» Shift · {count} cargas',dashTime:'» Shift · {time}s',shieldHit:'{count} carga',shieldHits:'{count} cargas',arenaCleared:'¡Arena despejada!',runScrap:'+{amount} de chatarra'},
        records:{line:'Récord {score} · Ronda {round}',scrapTotal:'{amount} de chatarra guardada',bestLabel:'Récord',scrapLabel:'Chatarra',bestValue:'{score} · R{round}'},
        boss:{phase:'{name} · Fase {phase}',miniboss:'Miniboss',arrival:'{name}',defeated:'Objetivo eliminado'},
        recovery:{title:'Partida interrumpida',body:'Se encontró una partida interrumpida.',continue:'Continuar partida',new:'Nueva partida'},
        messages:{powerStolen:'Poder desactivado: {name}',powerRestored:'Poder restaurado: {name}',weaponUp:'Arma nivel {level}'},
        categories:{all:'Todas las categorías',common:'Común',agile:'Ágil',heavy:'Pesado',ranged:'Distancia',support:'Soporte',hazard:'Peligro',summoner:'Invocador',elite:'Élite',miniboss:'Miniboss',boss:'Boss',invocation:'Invocación',control:'Control'},
        zones:{containment:'Contención',foundry:'La Fundición',bloom:'Floración',cryo:'Cubierta Criogénica',void:'El Vacío',ember:'Caída de Brasas',null:'Sector Nulo'},
        workshop:{title:'Taller',box:'Caja',gun:'Arma',bullet:'Bala',hint:'Solo apariencia: nada de aquí cambia cómo se juega.',buy:'Comprar {price}',equip:'Equipar',equipped:'Equipado',locked:'Faltan {price}',scrap:'{amount} de chatarra'},
        cosmetics:{
            box:{default:'Estándar',crimson:'Carmesí',toxic:'Tóxico',void:'Vacío',bone:'Hueso',gold:'Oro'},
            gun:{default:'Estándar',snub:'Corta',heavy:'Pesada',twin:'Doble',lance:'Lanza',gold:'Oro'},
            bullet:{default:'Estándar',plasma:'Plasma',ember:'Brasa',shard:'Esquirla',venom:'Veneno',gold:'Oro'}
        },
        upgrades:{maxHealth:['Estructura vital','+20 de vida máxima y recupera 50%'],heal:['Botiquín','Recupera toda la vida'],speed:['Movilidad','Velocidad de movimiento +12%'],damage:['Calibre','Daño permanente +5'],fireRate:['Cadencia','Intervalo de disparo -9%'],agility:['Recuperación','Recarga del salto -0.8s'],armor:['Blindaje','Daño recibido -8%'],shield:['Barrera','Bloquea el siguiente golpe'],dashDistance:['Distancia de dash','Alcance del dash +12%'],dashSpeed:['Velocidad de dash','Ejecución del dash +12%'],dashRecovery:['Recuperación de dash','Recarga del dash -0.35s'],dashShield:['Escudo de dash','Protección del dash +45ms'],shockDash:['Dash de impacto','El dash empuja enemigos'],trailBurn:['Rastro ardiente','El dash deja daño brevemente'],doubleDash:['Dash doble','Obtén una segunda carga de dash'],scatter:['Dispersión','Un proyectil más en un abanico más amplio'],lance:['Lanza','Los disparos perforan un enemigo más'],ricochet:['Rebote','Los disparos rebotan una vez más en los muros'],arc:['Arco','Los disparos saltan a enemigos cercanos'],siege:['Asedio','Disparos mucho más pesados, cadencia más lenta']},
        powers:{selfDestruct:['Autodestrucción','Q · 1 carga'],ghost:['Fantasma','Invulnerable y sin objetivo durante 7 segundos.'],overdrive:['Dash acelerado','Dash mejorado durante 8.5 segundos.'],backfire:['Contrafuego','Dispara hacia atrás durante 9 segundos.'],orbitals:['Orbitales','Cuatro orbitales protectores durante 10 segundos.'],timeFreeze:['Tiempo detenido','Enemigos muy ralentizados durante 6.5 segundos.'],bulletStorm:['Tormenta de balas','Disparo rápido durante 7 segundos.'],ricochet:['Rebote','Disparos rebotan una vez durante 9 segundos.'],chainLightning:['Cadena eléctrica','Disparos saltan a enemigos cercanos durante 8 segundos.'],gravityWell:['Pozo gravitatorio','Atrae enemigos durante 8 segundos.'],giant:['Modo gigante','Más grande, fuerte y lento durante 9 segundos.'],miniMode:['Modo mini','Más pequeño y rápido durante 9 segundos.'],piercingCore:['Núcleo perforante','Disparos atraviesan varios objetivos durante 9 segundos.'],clone:['Clon','Una copia dispara durante 8.5 segundos.']}
    }
};

const ROUND_NAMES = {
    'Horda':['Overrun','Desborde'],'Velocidad':['Blindside','Punto ciego'],'Artillería':['Crossfire','Fuego cruzado'],'Nido':['Feeding Time','Hora de caza'],'Terremoto':['Aftershock','Réplica'],'Oscuridad':['Blackout','Apagón'],'Arena pequeña':['Containment','Contención'],'Comida abundante':['Supply Drop','Suministros'],'Niebla':['Red Mist','Niebla roja'],'Doble velocidad':['Pressure Wave','Onda de presión'],'Enjambre':['Swarm','Enjambre'],'Cazadores':['Night Shift','Turno nocturno'],'Zona de guerra':['Kill Zone','Zona de fuego'],'Suelo inestable':['Hollow Floor','Suelo hueco'],'Arena cerrándose':['Lockdown','Cierre'],'Sin curación':['Last Light','Última luz'],'Regeneración enemiga':['Undying','Sin descanso'],'Explosiones':['Breach','Brecha'],'Caza del objetivo':['Marked','Marcado'],'Dos frentes':['Split Front','Frente dividido'],'Laberinto temporal':['No Man’s Land','Tierra de nadie'],'Tormenta de comida':['Feast','Banquete'],'Silencio':['Dead Signal','Señal muerta'],'Modo gigante':['Heavy Weather','Carga pesada'],'Modo miniatura':['Low Tide','Marea baja'],'Sin salto':['Grounded','En tierra'],'Terremotos':['Dead Ground','Tierra muerta'],'Robo de poder':['Power Cut','Corte de energía']
};

const FOOD_TEXT = {
    fry:[['Fries','Movement speed +15% for 4 seconds.'],['Papas fritas','Velocidad de movimiento +15% durante 4 segundos.']],cookie:[['Cookie','A small random boost for 5 seconds.'],['Galleta','Mejora aleatoria breve durante 5 segundos.']],pretzel:[['Pretzel','Jump recovery +35% for 7 seconds.'],['Pretzel','Recarga de salto +35% durante 7 segundos.']],sushi:[['Sushi','Projectile speed +30% for 7 seconds.'],['Sushi','Velocidad de proyectil +30% durante 7 segundos.']],bacon:[['Bacon','Fire rate +30% for 7 seconds.'],['Bacon','Cadencia +30% durante 7 segundos.']],kebab:[['Kebab','Damage +25% and piercing for 8 seconds.'],['Kebab','Daño +25% y perforación durante 8 segundos.']],hotdog:[['Hot Dog','Movement +20% and damage reduction for 7 seconds.'],['Hot dog','Movimiento +20% y reducción de daño durante 7 segundos.']],icecream:[['Ice Cream','Nearby enemies slowed for 6 seconds.'],['Helado','Enemigos cercanos ralentizados durante 6 segundos.']],cheese:[['Cheese','A slowing field for 7 seconds.'],['Queso','Campo de ralentización durante 7 segundos.']],taco:[['Taco','Shots ricochet once for 7 seconds.'],['Taco','Los disparos rebotan una vez durante 7 segundos.']],drumstick:[['Drumstick','Restore 25 health.'],['Pierna de pollo','Recupera 25 de vida.']],donut:[['Donut','Blocks the next hit.'],['Dona','Bloquea el siguiente golpe.']],chili:[['Chili','Movement and damage +55% for 4.5 seconds.'],['Chile','Movimiento y daño +55% durante 4.5 segundos.']],soup:[['Soup','Damage received -25% for 8 seconds.'],['Sopa','Daño recibido -25% durante 8 segundos.']],popcorn:[['Popcorn','Shots split on impact for 7 seconds.'],['Palomitas','Los disparos se dividen al impactar durante 7 segundos.']],garlic:[['Garlic','Close-range damage field for 8 seconds.'],['Ajo','Campo de daño cercano durante 8 segundos.']],coffee:[['Coffee','Movement and fire rate +25% for 5 seconds.'],['Café','Movimiento y cadencia +25% durante 5 segundos.']],nachos:[['Nachos','Projectile size +35% for 7 seconds.'],['Nachos','Tamaño de proyectil +35% durante 7 segundos.']],energy:[['Energy Drink','Refreshes jump and improves recovery.'],['Bebida energética','Recupera el salto y mejora su recarga.']],burger:[['Burger','Restore 55 health and gain damage reduction.'],['Hamburguesa','Recupera 55 de vida y reduce daño.']],pizza:[['Pizza','Regenerate health over 8 seconds.'],['Pizza','Regenera vida durante 8 segundos.']],cake:[['Cake','Restore 80 health.'],['Pastel','Recupera 80 de vida.']],grapes:[['Grapes','Creates three protective orbs.'],['Uvas','Crea tres orbes protectores.']],watermelon:[['Watermelon','Slow regeneration for 10 seconds.'],['Sandía','Regeneración lenta durante 10 segundos.']]
};

const LANGUAGE_KEY='deadboxLanguage';
if(!localStorage.getItem(LANGUAGE_KEY)&&localStorage.getItem('arenaLanguage'))localStorage.setItem(LANGUAGE_KEY,localStorage.getItem('arenaLanguage'));
let currentLanguage = localStorage.getItem(LANGUAGE_KEY) || 'en';
function t(path, vars={}) { let value=path.split('.').reduce((obj,key)=>obj?.[key],TRANSLATIONS[currentLanguage]); if(value==null)value=path.split('.').reduce((obj,key)=>obj?.[key],TRANSLATIONS.en)??path;if(typeof value!=='string')return value;return value.replace(/\{(\w+)\}/g,(_,key)=>vars[key]??`{${key}}`); }
function roundName(internal){const pair=ROUND_NAMES[internal];return pair?(currentLanguage==='es'?pair[1]:pair[0]):internal;}
function foodText(type){const pair=FOOD_TEXT[type];return pair?(currentLanguage==='es'?pair[1]:pair[0]):[type,''];}
function applyTranslations(root=document){root.querySelectorAll?.('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n);});document.documentElement.lang=currentLanguage;window.dispatchEvent(new CustomEvent('language_changed',{detail:currentLanguage}));}
function setLanguage(language){currentLanguage=TRANSLATIONS[language]?language:'en';localStorage.setItem(LANGUAGE_KEY,currentLanguage);for(const id of['language-main','language-pause','language-options']){const el=document.getElementById(id);if(el)el.value=currentLanguage;}applyTranslations();}
